<script setup lang="ts">
// /about/documents isn't CMS content — the live page is generated by
// WordPress's [general_resources use_documents=true] shortcode.
// This port uses the shared <GeneralResources> component and reuses
// the sidebar payload from the public /api/pages endpoint so the
// Documents ↔ Vision / Definitions / etc. navigation stays
// consistent with the catch-all renderer.

interface PageResponse {
  title: string
  menu_parent: { slug: string; title: string }
  children: Array<{ slug: string; title: string }>
}

const { t, locale } = useI18n()
const localePath = useLocalePath()

const { data: about } = await useAsyncData<PageResponse | null>(
  () => `about-sidebar-${locale.value}`,
  async () => {
    try {
      return await $fetch<PageResponse>('/api/pages/about', {
        query: { locale: locale.value }
      })
    } catch {
      return null
    }
  },
  { watch: [() => locale.value] }
)

useHead(() => ({ title: t('Documents') }))
</script>

<template>
  <div class="container page-content">
    <div class="with-sidebar">
      <aside class="sidebar">
        <nav class="stack" aria-label="Child pages navigation">
          <div>
            <ul class="stack | max-width-xs" role="list">
              <li v-if="about">
                <NuxtLink
                  class="font-size-lg"
                  :to="localePath(`/${about.menu_parent.slug}`)"
                >{{ about.menu_parent.title }}</NuxtLink>
              </li>
              <li v-for="child in about?.children ?? []" :key="child.slug">
                <NuxtLink
                  :class="{ 'current-link': child.slug === 'about/documents' }"
                  :to="localePath(`/${child.slug}`)"
                >{{ child.title }}</NuxtLink>
              </li>
            </ul>
          </div>
        </nav>
      </aside>

      <article>
        <h1>{{ t('Documents') }}</h1>
        <GeneralResources use-documents />
      </article>
    </div>
  </div>
</template>
